# Generated by Django 4.0.1 on 2022-03-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercertabla',
            name='url_image',
            field=models.ImageField(blank='', default='', upload_to='img_Profile/'),
        ),
    ]
