# Generated by Django 4.0.1 on 2022-01-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primertabla',
            old_name='edit',
            new_name='edited',
        ),
        migrations.AlterField(
            model_name='primertabla',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
