# Generated by Django 4.0.1 on 2022-02-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundatabla',
            name='format_img',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='segundatabla',
            name='url_img',
            field=models.ImageField(blank='', default='', upload_to='img/'),
        ),
    ]
