# Generated by Django 4.0.1 on 2022-02-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0002_alter_segundatabla_format_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundatabla',
            name='url_img',
            field=models.ImageField(blank='', default='', upload_to='assets/img'),
        ),
    ]
